# -*- coding: utf-8 -*-
"""web-scrapping-curso.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oKxH2Y2QS1_O3kxHJdtF5qoCfYV-ypVV
"""

# Ejemplo 1 - practica con la API de sunrise sunset
import requests

latitud = -34.6
longitud = -58.4
fecha = '1816-07-09' # AAA-MM-DD

# request y guardo la la respuesta de la API, el & es para separar las variables
response = requests.get(f'https://api.sunrise-sunset.org/json?lat={latitud}&lng={longitud}&date={fecha}')

datos = response.json()
print(datos)

sunset_status = datos['status']
print(f'Status: {sunset_status}')

datos['results']

sunset = datos['results']['sunset']
print(f'El {fecha} el sol se oculto a las: {sunset} (UTC)')

print("Iterando data datos['results']:")
for elemento in datos['results']:
    print(elemento)

# Ejemplo 2 con API de wikipedia
#!pip install --force-reinstall -v "wikipedia-api==0.5.8"
import wikipediaapi
print(wikipediaapi.__version__)

# instanciamos la clase wikipediaapi y utilizamos el metodo wikipedia con el parametro del idioma
IDIOMA = 'es'
wiki_wiki = wikipediaapi.Wikipedia(IDIOMA)

# usamos el metodo page para y hacemos un pedido con una palabra clave
PALABRA_CLAVE = 'programación'
wikipedia_programacion = wiki_wiki.page(PALABRA_CLAVE)

print(f'Wikipedia_programacion es un objeto de tipo: {type(wikipedia_programacion)}')

# resumen de la pagina
print(f'Titulo: {wikipedia_programacion.title}')
print(f'URL: {wikipedia_programacion.fullurl}')
print(f'Resumen: {wikipedia_programacion.summary}')

